### ISSUE TITLE
[Bug]: Postgres syntax error, when click on next page

### ISSUE THREAD

**Issue by RathanakSreang** [querymx/querym#156]
### 👟 Reproduction steps

When my table have more than 200 records, and I want to navigate to next page by click on next page button.
It should syntax error.

### 👍 Expected behavior

It should show me record of next page (page 2).

### 👎 Actual Behavior

It pop up  error "Error invoking remote method 'query': error: LIMIT #,#  syntax is not supported.
![Screenshot from 2023-10-05 18-40-22](https://github.com/querymx/querym/assets/12246079/75ae96d5-a30f-4ce1-999e-9d0ed7e2e84f)
"

**Comment by invisal** [comment]
Thanks for report the bug. I believe because PostgreSQL is using `LIMIT n OFFSET m;` instead of `LIMIT n,m`. We are working on the fix.

**Comment by invisal** [comment]
This has been fixed and will be released in next release next week,
