### ISSUE TITLE
[Bug]: How to run Project. I can't connect databest 

### ISSUE THREAD

**Issue by vicheanath** [querymx/querym#158]
### 👟 Reproduction steps

how to run it and what is the requirement or environment to run it, I don't see it CONTRIBUTING.md

here is my result from `yarn test:driver:mysql`

```js
➜  querym git:(change) ✗ yarn test:driver:mysql
yarn run v1.22.19
$ jest src/drivers/mysql
 PASS  src/drivers/mysql/_query.test.ts
 FAIL  src/drivers/mysql/_get_schema.test.ts
  ● get database schema

    expect(received).toContain(expected) // indexOf

    Expected value: "querymaster_test"
    Received array: ["mysql", "information_schema", "performance_schema", "sys", "xxxxx", "xxxx", "xxxx", "xxxxx", "xxxxx", "xxxxxx", …]

      12 | test('get database schema', async () => {
      13 |   const r = (await common.getSchema()).getSchema();
    > 14 |   expect(Object.keys(r)).toContain('querymaster_test');
         |                          ^
      15 |
      16 |   const currentDatabase = r['querymaster_test'];
      17 |   expect(Object.keys(currentDatabase.tables)).toEqual(['users']);

      at Object.<anonymous> (src/drivers/mysql/_get_schema.test.ts:14:26)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        2.243 s, estimated 3 s
Ran all test suites matching /src\/drivers\/mysql/i.
error Command failed with exit code 1.
```
mysql version : `mysql  Ver 8.1.0 for macos13.3 on arm64 (Homebrew)`

### 👍 Expected behavior

Success

### 👎 Actual Behavior

Error

**Comment by invisal** [comment]
Thanks for taking the interesting in running the project. Sorry for doing the poor job in providing the instruction on how to run the test. Because there is missing .sql file that I didn't provide in order to run the test.

Let me add those .sql file soon. Sorry again.

**Comment by vicheanath** [comment]
<img width="1229" alt="Screenshot 2023-10-05 at 8 04 06 PM" src="https://github.com/querymx/querym/assets/48352653/77ded415-89d7-4d42-b979-66efc17b7fe6">

That find now I can run it.

**Comment by vicheanath** [comment]
It problem with localhost not working I'm using IP instant on localhost it work.

**Comment by invisal** [comment]
Running it does not requires running test. The one that you run is for testing if mysql driving works. I thought you want to run automatic test. To run the project `npm run start`. :)

**Comment by invisal** [comment]
Do you want to contribute something or do you want to just use. If you want to just use, we have several pre-build package for Mac, Windows and Linux which does not require running from source code

**Comment by vicheanath** [comment]
I want to contribute. I'm newbie.

**Comment by invisal** [comment]
Thanks. You can use and drop what feature you want to implement in the issue. I can provide guide on how to achieve those feature. This will make thing easier for you.

**Comment by vicheanath** [comment]
I saw the feature  **Preview of geometry data on a map (in progress).**
I have some experience using  **open street maps**,

**Comment by vicheanath** [comment]
Does we have some kind of design or UI for this hold project?

**Comment by invisal** [comment]
> I saw the feature **Preview of geometry data on a map (in progress).** I have some experience using **open street maps**,

That would be nice. However, I am doing some refactoring that affect that area and will need to wait until it finish. Probably finish it by today. Since you interest in that part. I will provide more detail and assign it to you.

**Comment by vicheanath** [comment]
Yes, i will try it.

**Comment by invisal** [comment]
At the meantime, https://github.com/querymx/querym/issues/160 this issue is also good first issue
