### ISSUE TITLE
[Feature]: Missing JSON functions

### ISSUE THREAD

**Issue by vicheanath** [querymx/querym#169]
### Feature description

https://dev.mysql.com/doc/refman/8.0/en/json-function-reference.html

### 🎤 Pitch

https://dev.mysql.com/doc/refman/8.0/en/json-function-reference.html

**Comment by vicheanath** [comment]
- [ ] [->](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_json-column-path)	Return value from JSON column after evaluating path; equivalent to JSON_EXTRACT().		
- [ ] [->>](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_json-inline-path)	Return value from JSON column after evaluating path and unquoting the result; equivalent to JSON_UNQUOTE(JSON_EXTRACT()).		
- [ ] [JSON_ARRAY()](https://dev.mysql.com/doc/refman/8.0/en/json-creation-functions.html#function_json-array)	Create JSON array		
- [ ] [JSON_ARRAY_APPEND()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-array-append)	Append data to JSON document		
- [ ] [JSON_ARRAY_INSERT()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-array-insert)	Insert into JSON array		
- [ ] [JSON_CONTAINS()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-contains)	Whether JSON document contains specific object at path		
- [ ] [JSON_CONTAINS_PATH()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-contains-path)	Whether JSON document contains any data at path		
- [ ] [JSON_DEPTH()](https://dev.mysql.com/doc/refman/8.0/en/json-attribute-functions.html#function_json-depth)	Maximum depth of JSON document		
- [ ] [JSON_EXTRACT()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-extract)	Return data from JSON document		
- [ ] [JSON_INSERT()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-insert)	Insert data into JSON document		
- [ ] [JSON_KEYS()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-keys)	Array of keys from JSON document		
- [ ] [JSON_LENGTH()](https://dev.mysql.com/doc/refman/8.0/en/json-attribute-functions.html#function_json-length)	Number of elements in JSON document		
- [ ] [JSON_MERGE()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-merge)	Merge JSON documents, preserving duplicate keys. Deprecated synonym for JSON_MERGE_PRESERVE()		Yes
- [ ] [JSON_MERGE_PATCH()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-merge-patch)	Merge JSON documents, replacing values of duplicate keys		
- [ ] [JSON_MERGE_PRESERVE()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-merge-preserve)	Merge JSON documents, preserving duplicate keys		
- [ ] [JSON_OBJECT()](https://dev.mysql.com/doc/refman/8.0/en/json-creation-functions.html#function_json-object)	Create JSON object		
- [ ] [JSON_OVERLAPS()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-overlaps)	Compares two JSON documents, returns TRUE (1) if these have any key-value pairs or array elements in common, otherwise FALSE (0)	8.0.17	
- [ ] [JSON_PRETTY()](https://dev.mysql.com/doc/refman/8.0/en/json-utility-functions.html#function_json-pretty)	Print a JSON document in human-readable format		
- [ ] [JSON_QUOTE()](https://dev.mysql.com/doc/refman/8.0/en/json-creation-functions.html#function_json-quote)	Quote JSON document		
- [ ] [JSON_REMOVE()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-remove)	Remove data from JSON document		
- [ ] [JSON_REPLACE()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-replace)	Replace values in JSON document		
- [ ] [JSON_SCHEMA_VALID()](https://dev.mysql.com/doc/refman/8.0/en/json-validation-functions.html#function_json-schema-valid)	Validate JSON document against JSON schema; returns TRUE/1 if document validates against schema, or FALSE/0 if it does not	8.0.17	
- [ ] [JSON_SCHEMA_VALIDATION_REPORT()](https://dev.mysql.com/doc/refman/8.0/en/json-validation-functions.html#function_json-schema-validation-report)	Validate JSON document against JSON schema; returns report in JSON format on outcome on validation including success or failure and reasons for failure	8.0.17	
- [ ] [JSON_SEARCH()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-search)	Path to value within JSON document		
- [ ] [JSON_SET()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-set)	Insert data into JSON document		
- [ ] [JSON_STORAGE_FREE()](https://dev.mysql.com/doc/refman/8.0/en/json-utility-functions.html#function_json-storage-free)	Freed space within binary representation of JSON column value following partial update		
- [ ] [JSON_STORAGE_SIZE()](https://dev.mysql.com/doc/refman/8.0/en/json-utility-functions.html#function_json-storage-size)	Space used for storage of binary representation of a JSON document		
- [ ] [JSON_TABLE()](https://dev.mysql.com/doc/refman/8.0/en/json-table-functions.html#function_json-table)	Return data from a JSON expression as a relational table		
- [ ] [JSON_TYPE()](https://dev.mysql.com/doc/refman/8.0/en/json-attribute-functions.html#function_json-type)	Type of JSON value		
- [ ] [JSON_UNQUOTE()](https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html#function_json-unquote)	Unquote JSON value		
- [ ] [JSON_VALID()](https://dev.mysql.com/doc/refman/8.0/en/json-attribute-functions.html#function_json-valid)	Whether JSON value is valid		
- [ ] [JSON_VALUE()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-value)	Extract value from JSON document at location pointed to by path provided; return this value as VARCHAR(512) or specified type	8.0.21	
- [ ] [MEMBER OF()](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_member-of)	Returns true (1) if first operand matches any element of JSON array passed as second operand, otherwise returns false (0)	8.0.17

**Comment by invisal** [comment]
Thanks for working on this. We are really appreciating your work.
