### ISSUE TITLE
[Bug]: 🐞 Can't Click open link document and Style link poor

### ISSUE THREAD

**Issue by vicheanath** [querymx/querym#172]
### 👟 Reproduction steps

<img width="774" alt="Screenshot 2023-10-13 at 7 45 09 PM" src="https://github.com/querymx/querym/assets/48352653/7e0921c7-e6e2-47a1-b695-c9145654e852">

### 👍 Expected behavior

If we click on the link it should be open on the default browser

### 👎 Actual Behavior

Error

**Comment by invisal** [comment]
Do you want to fix this problem?

**Comment by vicheanath** [comment]
i will try it

**Comment by invisal** [comment]
This can be done in this file:
https://github.com/querymx/querym/blob/main/src/renderer/components/CodeEditor/functionTooltips.ts

The wrapper style classname is `code-tooltip`. To link outside the electron, you need to do `window.electron.openLink(...)`.
