### ISSUE TITLE
[Bug]: select autocomplete user table give user database.

### ISSUE THREAD

**Issue by Chhunneng** [querymx/querym#181]
### 👟 Reproduction steps

In Database have table **user** and **USER** of the Database. but when query give only result of Database **USER** 
<img width="873" alt="Screenshot 2023-10-23 at 14 45 30" src="https://github.com/querymx/querym/assets/47348453/55545fc7-7858-4433-9191-b400c9cc8da8">

<img width="886" alt="Screenshot 2023-10-23 at 14 45 52" src="https://github.com/querymx/querym/assets/47348453/b19d3a0d-6bff-4a26-8bcb-baf6a01938fe">

<img width="879" alt="Screenshot 2023-10-23 at 14 51 23" src="https://github.com/querymx/querym/assets/47348453/4a100c93-10d9-4dd1-8546-0bcb7405caee">

### 👍 Expected behavior

when selecting the **user** table from autocomplete should be `SELECT * FROM public."user"` instead of `SELECT * FROM user`

### 👎 Actual Behavior

Maybe this one is not a bug but just improves the behavior of autocomplete

<img width="873" alt="Screenshot 2023-10-23 at 14 45 30" src="https://github.com/querymx/querym/assets/47348453/1d78ea55-ebf3-42c3-837b-f4315f8dff70">
<img width="313" alt="Screenshot 2023-10-23 at 15 02 07" src="https://github.com/querymx/querym/assets/47348453/805a59ca-87ee-4aa7-b423-ffc83b8db716">

**Comment by invisal** [comment]
Thanks for reporting. I will look into it and see what I can improve.

**Comment by invisal** [comment]
I have fixed this problem. It should be available on next release (expected to be next week, 30th October 2023) with other auto complete improvement.
